Fix crash inside ObjectMap on SWF target
Okay, so the ObjectMap::toString method was dying for me on SWF target. Apparently trying to make the comparison

Type.getClass(ks[i]) == Array

caused the following error

TypeError: Error #1034: Type Coercion failed: cannot convert "my key string" to Array. This isn't an OpenFL build, just Haxe on its own compiling to a SWF.

If you can reproduce this, then try this pull request, it fixes it for me but I haven't tested it very much.